### ISSUE TITLE
It is not returning the `newStore` in the dispatch or update method 

### ISSUE THREAD

**Issue by rogefm** [mtmr0x/nucleo#31]
Well, the problem consist in: 
1. I try to use the update method, something like -> `const user = update('user')({ name: { firstName: 'Robert' }});` 
2. I receive status "OK"
3. Instead receive newStore inside `data` value, as showed on documentation example: 
```
{
  status: 'OK',
  errors: [],
  data: {
    name: {
      firstName: 'Robert',
      lastName: 'Nor'
    },
    age: 27
  },
}
```
I receive the same `data`, that I used into update method as a parameter, in another words, I receive
```
{
  status: 'OK',
  errors: [],
  data: {
    name: {
      firstName: 'Robert',
    },
  }
}
```

**Comment by rogefm** [comment]
Ah! And there aren't tests to cover these cases.

**Comment by mtmr0x** [comment]
This is a documentation issue, data should return what your tried to save. I'm fixing it and pushing. I'm also considering in the return object gives you the new data saved in store, I'll just figure out how I can do it safely.
